Streams - add single call crypt functions
libtom/libtomcrypt pull request #431
Opened 2018-07-30 05:20 UTC by buggywhip

Added single-call functions to crypt each of the stream ciphers using the \<cipher\>_memory() naming convention.

### Checklist
* [ x ] documentation is added or updated
* [ x ] tests are added or updated

2018-09-06 16:35 UTC, sjaeckel requested changes
LGTM :+1:

2018-09-06 16:35 UTC, sjaeckel commented on src/stream/chacha/chacha_test.c
> +   /* crypt in a single call using 64-bit counter with a value of 1 */
Can you please add a second testcase that also hits `chacha_ivctr32()`.

2018-09-10 09:37 UTC, sjaeckel commented
I took the freedom to rebase everything on top of develop and clean up the duplicate commits :)

2018-09-10 09:47 UTC, buggywhip commented
> On 10Sep, 2018, at 2:37 AM, Steffen Jaeckel <notifications@github.com> wrote:
> 
> I took the freedom to rebase everything on top of develop and clean up the duplicate commits :)
> 
Thanks.  ...but the git log graph looks funny.  ...and certainly not like it was after my rebase/squash.  ???  May I assume it is fixable?  ...how?

2018-09-10 15:26 UTC, sjaeckel reviewed
I think we should include these `xx_memory()` implementations in the single c files where there's only a single file for now!
@karel-m what do you think?
@buggywhip sorry, I didn't see that before!

2018-09-10 21:25 UTC, karel-m commented
> I think we should include these `xx_memory()` implementations in the single c files where there's only a single file for now!

I am for keeping `xx_memory()` **always** in a separate `.c` file. It has obvious advantages (smaller code) when using static linking.

2018-09-11 06:11 UTC, sjaeckel commented
Good point I didn't think about!
So let's keep it like that.

2018-09-21 19:03 UTC, merged