Improve SSE4.1/AES-NI support
libtom/libtomcrypt pull request #644
Opened 2024-03-31 07:29 UTC by tbvdm

The CryptX Perl module contains a vendored copy of libtomcrypt. It uses `-msse4.1 -maes` to enable AES-NI support. The problem is that these flags are used for *all* source files. This results in `SIGILL` crashes on CPUs without SSE4.1.

I think the solution is for CryptX to use `-msse4.1 -maes` only for `aesni.c`. But this is not possible without several changes to libtomcrypt. This pull request is a proposal for those changes.

The primary change is in how SSE4.1 is detected. Currently libtomcrypt checks `__SSE4_1__`. But this requires that `-msse4.1` is used for multiple source files. Moreover, it's a compile-time check, not a run-time one. I think it would be better to detect SSE4.1 with `cpuid`.

Then there is the build procedure. I came up with the following approach. By default, AES-NI support is disabled. To enable it, add `-DLTC_AES_NI` to `CFLAGS` and set the required compiler flags in `CFLAGS_AES_NI` (typically `-maes -msse4.1`). For example:

```
make -f makefile.unix CFLAGS=-DLTC_AES_NI CFLAGS_AES_NI="-maes -msse4.1"
```

### Checklist

* [x] documentation is added or updated
* [x] tests are added or updated

2024-03-31 08:04 UTC, tbvdm commented
Maybe I should cc @karel-m

2024-04-02 22:33 UTC, sjaeckel commented
Did you check whether #641 fixes this already?

2024-04-02 22:35 UTC, sjaeckel commented
Did you try the proposed change of #641 and whether this maybe fixes it already?

2024-04-03 19:15 UTC, tbvdm commented
#641 doesn't help, unfortunately. Here is a crash from the `fix-perl-cryptx-99` branch on a machine without SSE4.1 (running OpenBSD):

```
$ git clone -b fix-perl-cryptx-99 https://github.com/libtom/libtomcrypt.git
$ cd libtomcrypt
$ make -f makefile.unix CFLAGS="-maes -msse4.1"
$ cd ..
$ cat test.c
#include <tomcrypt.h>

int main(void)
{
	register_cipher(&aes_desc);
	gcm_test();
}
$ cc -I libtomcrypt/src/headers libtomcrypt/libtomcrypt.a test.c
$ ./a.out
Illegal instruction (core dumped)
$ egdb -q a.out a.out.core
Reading symbols from a.out...
(No debugging symbols found in a.out)
[New process 186382]
Core was generated by `a.out'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x00000a534708a0f0 in gcm_test ()
(gdb) x/i $pc
=> 0xa534708a0f0 <gcm_test+1696>:	ptest  %xmm0,%xmm0
```

2024-06-12 02:42 UTC, HaikalAzaim commented
Did you try the proposed change of https://github.com/libtom/libtomcrypt/pull/641 and whether this maybe fixes it already?

2024-06-12 08:41 UTC, sjaeckel commented
Sorry for the long delay.

> #641 doesn't help, unfortunately. Here is a crash from the `fix-perl-cryptx-99` branch on a machine without SSE4.1 (running OpenBSD):
> 
> ```
> $ git clone -b fix-perl-cryptx-99 https://github.com/libtom/libtomcrypt.git
> $ cd libtomcrypt
> $ make -f makefile.unix CFLAGS="-maes -msse4.1"
> $ cd ..
> $ cat test.c
> #include <tomcrypt.h>
> 
> int main(void)
> {
> 	register_cipher(&aes_desc);
> 	gcm_test();
> }
> $ cc -I libtomcrypt/src/headers libtomcrypt/libtomcrypt.a test.c
> $ ./a.out
> Illegal instruction (core dumped)
> $ egdb -q a.out a.out.core
> Reading symbols from a.out...
> (No debugging symbols found in a.out)
> [New process 186382]
> Core was generated by `a.out'.
> Program terminated with signal SIGILL, Illegal instruction.
> #0  0x00000a534708a0f0 in gcm_test ()
> (gdb) x/i $pc
> => 0xa534708a0f0 <gcm_test+1696>:	ptest  %xmm0,%xmm0
> ```

FMU that's a different problem. You can also see that it fails in `gcm_test()` and not in AES related code.

A valid test-case for AES-NI would be to first configure&build the library as you did and then execute this:

```c
#include <tomcrypt.h>

int main(void)
{
	aes_test();
}
```

WARNING: I checked the disassembly in the past and was too lazy to re-check now, so I hope the following statement is still correct :) Please correct me if I'm wrong!

Regarding what you're seeing: You're explicitly enabling SSE4.1, which allows the compiler to generate SSE-specific instructions.

The following code comes from an era when compilers were not yet that smart:

https://github.com/libtom/libtomcrypt/blob/f7e6519fae1e11ff5ff9d36c84101a673002133b/src/encauth/gcm/gcm_mult_h.c#L19-L41

By enabling `-msse4.1` at compile time you did not enable that exact path in the source code (via the define etc.), but the compilers got so smart that they generate exactly those assembly instructions from the "default code path" (even when `LTC_GCM_TABLES_SSE2` is not defined).

You should also be able to reproduce this failure with the latest release (master branch) that has no AES-NI support yet.

Maybe also try to add debug information when building the library to see where exactly it breaks? `make -f makefile.unix CFLAGS="-maes -msse4.1 -g3"`

2024-06-12 08:54 UTC, sjaeckel commented
And also you're right with this PR... now I understand the purpose :) 

With this we have now "proper" runtime support for AES-NI. It allows to build the rest of the library for all amd64 (also non SSE) and only requires the AES-NI related parts to be built with SSE4.1 support.

2024-06-12 09:09 UTC, sjaeckel requested changes
LGTM

2024-06-12 09:09 UTC, sjaeckel commented on README.md
> +You want to enable AES-NI support:
```suggestion
You want to enable AES-NI support, but compile the rest of the library without the requirement for SSE4.1:
```

2024-06-24 19:25 UTC, tbvdm commented
> Sorry for the long delay.

No worries. Thanks for looking at this.

> FMU that's a different problem. You can also see that it fails in `gcm_test()` and not in AES related code.
> 
> [...]
> 
> Regarding what you're seeing: You're explicitly enabling SSE4.1, which allows the compiler to generate SSE-specific instructions.

That's precisely the point: currently, if you want to enable AES-NI support, you need to enable SSE4.1 unconditionally for the whole source tree.

This is especially relevant when building binary packages. The same binary package should (ideally) be able to run different CPUs with different capabilities.

> And also you're right with this PR... now I understand the purpose :)
> 
> With this we have now a "proper" runtime check for AES-NI. It allows to build the rest of the library for all amd64 (also non SSE) and only requires the AES-NI related parts to be built with SSE4.1 support.

Yes, exactly. :)

2024-06-24 19:29 UTC, tbvdm commented
I've force-pushed a new commit that includes the change you requested.

2024-06-26 18:18 UTC, sjaeckel reviewed
Uhm ... I've just had a third look at this and wouldn't it even make sense to compile `aesni.c` always with those flags? ... but then we'd need some kind of configure step which determines the target architecture ... What do you think?

Also I've only now realized that there's no CMake support for this feature, that's why I haven't merged it yet.

2024-06-29 18:09 UTC, tbvdm commented
Why don't we use target attributes? See the new commit. This avoids the need for flags altogether. You only have to make sure that `LTC_AES_NI` is defined. For example:

```
make -f makefile.unix CFLAGS=-DLTC_AES_NI
```

I defined `__attribute__` away for MSVC. Also, MSVC does not need flags or attributes to enable SSE4.1 and AES intrinsics.

(However, I don't think MSVC will work anyway, because apparently it does not support inline assembly on x64. So the `cpuid` call will fail. I think the solution is to call `cpuid` through an intrinsic.)

2024-08-29 17:31 UTC, levitte requested changes
ltc's source checker in helper.pl doesn't like it when you redefine compiler specific symbols.  It may be better to make an LTC macro for what you want, like this.

2024-08-29 17:31 UTC, levitte commented on src/ciphers/aes/aesni.c
> +#endif
```suggestion
#if !(defined(__GNUC__) || defined(__clang__))
#define LTC_ATTRIBUTE(x)
#else
#define LTC_ATTRIBUTE(x) __attribute__(x)
#endif
```

2024-08-29 17:31 UTC, levitte commented on src/ciphers/aes/aesni.c
> +__attribute__((__target__("aes,sse4.1")))
```suggestion
LTC_ATTRIBUTE((__target__("aes,sse4.1")))
```

2024-08-29 17:31 UTC, levitte commented on src/ciphers/aes/aesni.c
> +__attribute__((__target__("aes")))
```suggestion
LTC_ATTRIBUTE((__target__("aes")))
```

2024-08-29 17:31 UTC, levitte commented on src/ciphers/aes/aesni.c
> +__attribute__((__target__("aes")))
```suggestion
LTC_ATTRIBUTE((__target__("aes")))
```

2024-08-31 12:54 UTC, tbvdm commented
I've pushed a new commit that is rebased on current `develop`, squashes the two commits in this PR, and includes @levitte's suggestions.

2024-08-31 13:14 UTC, sjaeckel commented on src/ciphers/aes/aesni.c
> +#endif
Do we maybe want this directly in one of the header files? `tomcrypt_cfg.h`!?

2024-08-31 13:16 UTC, sjaeckel requested changes
Thanks a lot for the improvements on this and thanks for the PR. Looks very good now.

(and please rebase on top of current develop :) )

2024-09-01 17:11 UTC, tbvdm commented
Done!

2024-09-01 17:36 UTC, sjaeckel approved these changes

2024-09-01 17:43 UTC, sjaeckel commented
This also supersedes #641 right?

2024-09-01 19:39 UTC, tbvdm commented
Yes, I believe it does.

2024-09-02 06:52 UTC, sjaeckel commented
Before merging this I have one more question:

Wouldn't it now make sense to enable this by default on x86/amd64?
If yes, we should change the compile-time-switch to disable if not desired.

Btw. thanks (and sorry) @tbvdm for doing this lengthy exercise with us ;)

2024-09-02 08:51 UTC, karel-m commented
@tbvdm could you please rebase this PR's branch on top of current develop? I will try to make a dev release of CryptX perl bindings with this patch to check what will happen on cpantesters & co.

2024-09-02 09:20 UTC, sjaeckel commented
> Wouldn't it now make sense to enable this by default on x86/amd64?

@karel-m I'd also like your opinion on this

2024-09-02 10:31 UTC, karel-m commented
> Wouldn't it now make sense to enable this by default on x86/amd64?

I do not have a strong opinion on this but I would rather keep it off by default,

According to my experiance you basically need:
- to found out (or guess) whether your compiler suupports AESNI (in my CryptX I turn it on only for gcc/clang/llvm v5+)
- than the compiler needs a special options e.g. `-msse4.1 -maes` for gcc/clang/llvm (OK, perhaps using target attributes might help here, but I'm not sure how it will work on older or less common compilers)
- on top of that you will simply pass also `-DLTC_AES_NI`

2024-09-02 10:34 UTC, levitte commented
I think I'm leaning on the cautious side re the default.  @karel-m said it a lot better

2024-09-02 11:57 UTC, sjaeckel commented
Alright, then we'll stay away from the danger zone and leave it off by default ;)

@tbvdm I took the liberty to rebase and force-push your branch, I hope that's OK

2024-09-02 12:26 UTC, merged

2024-09-02 13:11 UTC, sjaeckel commented
I guess we forgot to enable this in the CI build ... ;)

https://github.com/libtom/libtomcrypt/blob/ce904c86efae8ecbf167e3e20babdd4cfd5511d7/.github/workflows/main.yml#L41

2024-09-02 20:02 UTC, tbvdm commented
Thanks for merging this. :)

Yes, it seems I missed main.yml when I grepped the tree for relevant files.