Add SM4 block cipher [reboot]
libtom/libtomcrypt pull request #657
Opened 2024-08-20 05:45 UTC by levitte

SM4 (formerly SMS4)[1] is a block cipher used in the Chinese
National Standard for Wireless LAN WAPI (Wired Authentication
and Privacy Infrastructure).
--from wikipedia

### Checklist

* [ ] documentation is added or updated
* [x] tests are added or updated

2024-08-20 09:12 UTC, levitte commented
I believe this is ready for review

2024-08-20 09:14 UTC, levitte commented
All fixups squashed too

2024-08-20 14:08 UTC, levitte commented
Hmmmm, coveralls says that only 1 line in the new code is covered...  huh???

2024-08-21 17:13 UTC, sjaeckel commented
> Hmmmm, coveralls says that only 1 line in the new code is covered... huh???

oopsie :D race condition on the cipher ID with the addition of DES-X via #587 :grimacing:

2024-08-21 17:13 UTC, sjaeckel commented on src/ciphers/sm4.c
> +    27,
```suggestion
    28,
```

2024-08-22 07:39 UTC, levitte commented on src/ciphers/sm4.c
> +    27,
Thank you.  Fixed

2024-08-26 13:07 UTC, sjaeckel requested changes

2024-08-26 13:07 UTC, sjaeckel commented on src/ciphers/sm4.c
> +}
Do we really need a runtime decision on that? We've the `LOAD` and `STORE` macros for that purpose.

2024-08-26 13:07 UTC, sjaeckel commented on src/ciphers/sm4.c
> +#endif
Either we should remove one of the two options, or make it a real compile time decision (but only if there exists a specific reason why to use one or the other).

2024-08-26 13:07 UTC, sjaeckel commented on src/ciphers/sm4.c
> +    return B ^ rol(B, 13) ^ rol(B, 23);
```suggestion
    return B ^ ROLc(B, 13) ^ ROLc(B, 23);
```

2024-08-26 13:07 UTC, sjaeckel commented on src/ciphers/sm4.c
> +   */
```suggestion
```

2024-08-26 13:07 UTC, sjaeckel commented on src/ciphers/sm4.c
> +/* commit time: $Format:%ai$ */
```suggestion
```

2024-08-26 13:07 UTC, sjaeckel commented on src/ciphers/sm4.c
> +    return B ^ rol(B, 2) ^ rol(B, 10) ^ rol(B, 18) ^ rol(B, 24);
```suggestion
    return B ^ ROLc(B, 2) ^ ROLc(B, 10) ^ ROLc(B, 18) ^ ROLc(B, 24);
```

2024-08-26 13:07 UTC, sjaeckel commented on src/ciphers/sm4.c
> +void sm4_setkey(struct sm4_key *sm4, const unsigned char *key)
```suggestion
static void sm4_setkey(struct sm4_key *sm4, const unsigned char *key)
```

2024-08-26 13:07 UTC, sjaeckel commented on src/ciphers/sm4.c
> +    }
```suggestion
    for (i = 0; i < 32; ++i) {
        X[i+4] = F(X+i, rk[i]);
    }
```

2024-08-26 13:07 UTC, sjaeckel commented on src/ciphers/sm4.c
> +    ret = sm4_memcmp(output, ciphertext, 16);
We should use `compare_testvector()` instead. Like that all the other invocations of `sm4_printf()`, `test()`, `result()` etc. can also go.

2024-08-27 06:06 UTC, levitte commented on src/ciphers/sm4.c
> +#endif
I'm choosing the former, and use LOAD32H / STORE32H, to align with how it's done in other ciphers

2024-08-27 06:40 UTC, levitte commented on src/ciphers/sm4.c
> +}
Removing them all

2024-08-29 20:42 UTC, sjaeckel commented
What do you think of those two commits? Nonsense or useful? Please rebase&squash the useful ones on top of develop, then I'll merge.

2024-08-29 20:46 UTC, sjaeckel approved these changes

2024-08-30 03:30 UTC, levitte commented
They are all fine, so I adopted (squashed) them all

2024-08-30 03:31 UTC, levitte commented
Now also rebased on a fresher develop

2024-08-31 13:13 UTC, merged