Make the definition of LTC_WIN32_BCRYPT private
libtom/libtomcrypt pull request #660
Opened 2024-08-20 13:14 UTC by levitte

1. It's internal anyway, so doesn't quite need to be reflected in a
   public header file.
2. This makes it easy for someone build this library to choose not
   to use BCryptGenRandom() by simply definining LTC_NO_WIN32_BCRYPT,
   which was hard to reflect in an unmodified public header file.

Alternative to #653

2024-08-21 08:33 UTC, sjaeckel requested changes
Thanks! That looks a lot better IMO.

After having a quick glance at `tomcrypt_cfg.h` there's most likely a few other things that could be made private.  ... and maybe also a discussion to open, whether it'd make sense to split this then up in two different private headers, one for headers and one for cfg ... or whether cfg should be private in the first place!? ... but let's merge this first to unblock @karel-m

2024-08-21 08:33 UTC, sjaeckel commented on src/headers/tomcrypt_private.h
> + * If CryptGenRandom() is desired, define LTC_NO_WIN32_BCRYPT when building
```suggestion
 * On Windows, choose whether to use CryptGenRandom() [older Windows versions]
 * or BCryptGenRandom() [newer Windows versions].
 * If CryptGenRandom() is desired, define LTC_NO_WIN32_BCRYPT when building.
```

2024-08-21 09:20 UTC, levitte commented
I don't see anything wrong with `tomcrypt_cfg.h` being public.

However, `tomcrypt_custom.h` could be a candidate to be made private, but I'm unsure, 'cause if a choice made there affects *other public headers* (such as what the applications get to see), then it isn't a candidate.

2024-08-21 17:20 UTC, sjaeckel approved these changes
Please squash & force-push, no need for that silly co-authored tag ;)

Btw. you're free to push feature branches directly to this repo, no need for your fork!

2024-08-22 07:34 UTC, levitte commented
> Btw. you're free to push feature branches directly to this repo, no need for your fork!

Oh!  Yeah, that might be practical.  Thank you.

2024-08-22 07:36 UTC, levitte commented
Squashed and ready to be merged :-)

2024-08-26 12:49 UTC, merged